### PR TITLE
PDF export to PDF/A-1

### PR DESCRIPTION
**Pull request by florianajir**

### CODE REVIEW

**Comment by navytux** [comment]
@florianajir cloudooo repository on github.com, as its description says, is only a read-only mirror of https://lab.nexedi.com/nexedi/cloudooo . I suggest you to submit your pull request there.

Thanks,
Kirill

**Comment by navytux** [comment]
@florianajir FYI I've submitted your patch here:

https://lab.nexedi.com/nexedi/cloudooo/merge_requests/4

**Comment by gmonnerat** [comment]
@florianajir Thank for the patch, could please describe more or improve the commit message with reason of "export PDF/A-1 instead of PDF 1.4" ?

Thank you in advance.

**Comment by florianajir** [comment]
My commit description is not good because of PDF/A-1 was based on PDF v1.4, but is standardized and better for long time preservation documents,
I done this patch to convert odt documents to pdf/a-1 from the archival system [as@lae](https://adullact.net/projects/asalae/)
Maybe a cloudooo refactoring can be done to choose between pdf format/version but I don't know much about cloudooo.

If you need more informations about PDF/A-1, you can read this article : http://www.digitalpreservation.gov/formats/fdd/fdd000125.shtml

**Comment by fdiary** [comment]
PDF/A-1 is not a upper-compatible format of PDF v1.4. For example, transparent objects and layers are  supported in PDF v1.4 but not supported in PDF/A-1. (They are supported in PDF/A-2 that is not supported by LibreOffice). So I am not sure if this behaviour change is ALWAYS good or not.

Ideally, cloudooo API should accept some parameters so that the user can control the behaviour like PDF or PDF/A, image compression quality etc. PR in this direction is highly welcome !

But until then, I personally can accept this change (but without white-space-only change that is not related to this topic).

**Comment by gmonnerat** [comment]
Thank you @florianajir and @fdiary.

I ran all tests and are passing:

All Tests 153
Failures 0
Errors 2

OBS: The two errors are not related to this patch and we also have it in master. So, I will merge.

I will fix this errors in another branch.

**Comment by florianajir** [comment]
Like @fdiary said we could imagine to let the initial `impress_pdf_Export` filter configuration and export pdf/a-1 on the new filter `pdf_Export`.

If you're ok, I'll edit my PR.

thanks for suggestions.

**Comment by jerome-nexedi** [comment]
I am closing this, since the patch was applied long ago in 974e5f17

**Pull request closed without merging**
